### PR TITLE
More QuTune and ICCMR entries

### PR DESCRIPTION
**Pull request by Itaborala**
Late night insomnia, Might as well just finally add some entries here.
@omarcostahamido let me know if the format is adequate.

- New Events (All concerts from QuTune project in late 2022 - Early 2024)
- New People (All people involved in the events above)
- New Works (All compositions of the events above, including two chamber music works)
- New Writings (Some important ICCMR Papers + Master Thesis)
- New Software (Q1Synth, OSC-Qasm, PaulisMIDI, VQH, quantumaudio)

### NEW INSTITUTIONS FOLDER
I'm suggesting the creation of a new folder called institutions, containing research centers (ICCMR, CQTA, CEIS20, etc) and Companies (Moth, IQM, IBMQ, Quantinuum) that were involved in some of the events and works.

### CODE REVIEW

**Comment by Itaborala** [comment]
Removed the institutions folder idea for a later time

**Comment by Itaborala** [comment]
Hi, Just an "up" on this thread. I'm going to mention this community at a talk today :)
Is there anything I can do to assist in this PR?

**Comment by omarcostahamido** [comment]
reviewing it 🫡

**Comment by omarcostahamido** [comment]
ok, so I really like the idea of listing ensembles, but the collective person entry is a bit problematic in a sense:
- on the one hand if the group composition changes, which is not unlikely, there are performers that may either not be credited or miscredited... then you would have to go and update the ensemble page to clarify that, and we don't have time for that.
- on the other hand the boundary between ensemble, group, or institution can be a bit blurred at times, and as such it may not be fair to list some groups and not others. let's postpone the group types for now. we already have plenty of database entry types to loose lots of time!

Thank you again for suggesting this!

**Comment by omarcostahamido** [comment]
@Itaborala please share here the links for:
📍Ligeti Zentrum Inauguration
📍Many Musics, Quantum Worlds
📍Tensorial Ripples
📍Turning Points_ Sound Unwrapped

**Comment by omarcostahamido** [comment]
also we need an waybackmachine link for these externals links:
https://web.archive.org/save
note to self: add some instructions about this!
see #71

**Comment by Itaborala** [comment]
Ligeti Zentrum - https://ligetizentrum.hfmt-hamburg.de/index.php/multiverse-symphony/
Many Musics - https://iklectikartlab.com/many-musics-quantum-worlds/
Tensorial Ripples - https://youtu.be/PMUNIBs7T04?si=WEmo4r0HVXVtqDez
Sound Unwrapped - https://londonsinfonietta.org.uk/whats-on/turning-points-sound-unwrapped

**Review by omarcostahamido — APPROVED** [review]
thank you so much again.
loved the new icon for thesis, and newspaper articles.
great opportunity to think about how to organize and simplify this again.
(meaning that i opened several new issues, haha!)
In structural terms though, I think we should really keep these 5 categories and keep building on them.
Still left quantum sounds symposium event at icfo mostly incomplete, but hey, this is a digital garden after all! meaning it is an open book and work in progress, and should be accessible for people to contribute to.

**Pull request merged**
